import { model, Schema } from "mongoose";

const parroquiaSchema = new Schema({
  nombre: {
    type: String,
    required: true,
    enum: [
      "NANEGAL",
      "PACTO",
      "GUALEA_Y_NANEGALITO",
      "EL_CONDADO",
      "PONCEANO",
      "SAN_ANTONIO_DE_PICHINCHA",
      "NONO",
      "COTOCOLLAO",
      "POMASQUI",
      "CALACALI",
      "COMITE_DEL_PUEBLO",
      "CARCELEN",
      "CALDERON",
      "LLANO_CHICO",
      "NAYON",
      "ZAMBIZA",
      "PUELLARO",
      "CHAVEZPAMBA",
      "ATAHUALPA",
      "SAN_JOSE_DE_MINAS",
      "PERUCHO_Y_GUAYLLABAMBA",
      "LA_CONCEPCION",
      "MARISCAL_SUCRE",
      "BELISARIO_QUEVEDO",
      "SAN_ISIDRO_DEL_INCA",
      "RUMIPAMBA",
      "KENNEDY",
      "INIAQUITO",
      "COCHAPAMBA_Y_JIPIJAPA",
      "PUENGASI",
      "CENTRO_HISTORICO",
      "SAN_JUAN",
      "LA_LIBERTAD_E_ITCHIMBIA",
      "CHILIBULO",
      "SAN_BARTOLO",
      "CHIMBACALLE",
      "LA_ARGELIA",
      "SOLANDA",
      "LLOA",
      "LA_MENA",
      "LA_MAGDALENA",
      "LA_FERROVIARIA",
      "CHILLOGALLO",
      "GUAMANI",
      "QUITUMBE",
      "TURUBAMBA",
      "LA_ECUATORIANA",
      "CONOCOTO",
      "PINTAG",
      "AMAGUANIA",
      "ALANGASÍ",
      "GUANGOPOLO_Y_LA_MERCED",
      "TUMBACO",
      "CUMBAYA",
      "PIFO",
      "YARUQUI",
      "EL_QUINCHE",
      "PUEMBO",
      "CHECA_Y_TABABELA",
    ],
    unique: true,
  },
  votantes: [
    {
      type: Schema.Types.ObjectId,
      ref: "Votante",
      default: null,
    },
  ],
});

export default model("Parroquia", parroquiaSchema);
